allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@crownshy/api-client@0.0.8'
  - '@crownshy/api-client@0.0.10'
  - '@crownshy/api-client@0.0.11'
  - '@crownshy/api-client@0.0.12'
onlyBuiltDependencies:
  - esbuild
packages:
  - packages/*
